name: Publish Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
  create-release:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true
      - name: List Files (Check Flat Structure)
        run: ls -R build
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
